name: Build Matrix of Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    strategy:
      matrix:
        image_type: [minimal-notebook, scipy-notebook]
        image_tag: [lab-3.6.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Container image
        run: |
          platarch=linux/arm64/v8,linux/amd64
          docker buildx build \
            --platform=$platarch \
            --load \
            --tag ghcr.io/leemartin77/jupyter-env-config:${{ matrix.image_type }}-${{ matrix.image_tag }} \
            --build-arg IMAGE_TYPE=${{ matrix.image_type }} \
            --build-arg IMAGE_TAG=${{ matrix.image_tag }} \
            .

      - name: Push Version
        run: docker manifest push ghcr.io/leemartin77/jupyter-env-config:${{ matrix.image_type }}-${{ matrix.image_tag }}
